version: '3'

name: onlymemes

services:
  database:
    image: postgres:15.3-alpine3.18
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: onlymemes
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - ./tmp:/var/lib/postgresql/data

  bunbackend:
    build: ./backend
    depends_on:
      - database
    ports:
      - "3001:3001"

  frontend:
    build: ./frontend
    ports:
      - "80:80"

networks:
  default:
    name: onlymemes_network